# Generated by Django 3.2.20 on 2023-10-27 09:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', cloudinary.models.CloudinaryField(default='card_placeholder', help_text='Please upload image with width 315px x height 200px', max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('short_summary', models.TextField(blank=True, max_length=500)),
                ('long_summary', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
