# Generated by Django 3.2.20 on 2023-08-14 10:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', cloudinary.models.CloudinaryField(default='hero_placeholder', max_length=255, verbose_name='image')),
                ('tagline_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OverviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', cloudinary.models.CloudinaryField(default='card_placeholder', max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('summary', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
