# Generated by Django 3.2.20 on 2023-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Enter 1, 2, or 3', unique=True),
        ),
    ]
