# Generated by Django 3.2.20 on 2023-09-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_carousel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='tagline_text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
