# Generated by Django 3.2.20 on 2023-09-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_carousel_tagline_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
