# Generated by Django 3.2.20 on 2023-09-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230929_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscard',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='newscard',
            name='summary',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
