# Generated by Django 3.2.20 on 2023-10-16 13:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230929_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestResearchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', cloudinary.models.CloudinaryField(default='card_placeholder', max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, max_length=250)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RenameModel(
            old_name='NewsCard',
            new_name='LatestNewsCard',
        ),
    ]
