# Generated by Django 3.2.20 on 2023-10-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20231016_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnewscard',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='latestnewscard',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='latestresearchcard',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='latestresearchcard',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
