# Generated by Django 3.2.20 on 2023-10-26 10:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20231026_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnewscard',
            name='card_image',
            field=cloudinary.models.CloudinaryField(default='card_placeholder', help_text='Please upload image with width 315px x height 200px', max_length=255, verbose_name='image'),
        ),
    ]
