# Generated by Django 3.2.20 on 2023-10-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_latestnewscard_card_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestNewsCard',
        ),
    ]
