# Generated by Django 3.2.20 on 2023-10-12 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0002_delete_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_of_address', models.CharField(max_length=200)),
                ('second_line_address', models.CharField(default='Enter second line of address', max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
            ],
        ),
    ]
