# Generated by Django 3.2.20 on 2023-09-25 10:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=2000)),
                ('thumbnail', cloudinary.models.CloudinaryField(default='publication_placeholder', max_length=255, verbose_name='image')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('publication', models.CharField(max_length=255)),
                ('authors', models.TextField(max_length=2000)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
