# Generated by Django 3.2.20 on 2023-09-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_publication_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(help_text='For consistency please use Arial font,             size 12, line height 1.4'),
        ),
    ]
