# Generated by Django 3.2.20 on 2023-08-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_category',
            field=models.CharField(choices=[('Centre Director', 'Centre Director'), ('Research Fellow', 'Research Fellow'), ('Visiting Fellow', 'Visiting Fellow')], default='Centre Director', max_length=100),
        ),
    ]
