# Generated by Django 3.2.20 on 2023-09-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_profile_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='web_link',
            field=models.TextField(default='www.google.com', max_length=2000),
        ),
    ]
