# Generated by Django 3.2.20 on 2023-09-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_profile_web_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='web_link',
            field=models.TextField(default='www.google.com', help_text="Please enter full web address including 'https://'", max_length=2000),
        ),
    ]
