# Generated by Django 3.2.20 on 2023-09-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_profile_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='discipline',
        ),
    ]
