# Generated by Django 3.2.20 on 2023-09-20 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_remove_profile_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 13, 56, 55, 729588, tzinfo=utc)),
        ),
    ]
