# Generated by Django 3.2.20 on 2023-09-22 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20230920_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 43, 27, 538287, tzinfo=utc)),
        ),
    ]
