# Generated by Django 3.2.20 on 2023-09-25 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_alter_profile_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 10, 17, 59, 956214, tzinfo=utc)),
        ),
    ]
