# Generated by Django 3.2.20 on 2023-09-27 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20230927_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 18, 27, 7, 538818, tzinfo=utc)),
        ),
    ]
