# Generated by Django 3.2.20 on 2023-09-29 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_alter_profile_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 13, 8, 59, 937285, tzinfo=utc)),
        ),
    ]
