# Generated by Django 3.2.20 on 2023-10-16 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_auto_20231016_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 8, 52, 58, 589314, tzinfo=utc)),
        ),
    ]
