# Generated by Django 3.2.20 on 2023-10-17 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_alter_profile_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 7, 50, 14, 979529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
